"""
WAF Fingerprints

Fingerprint database used by the
WAF Detection module.
"""

# ==========================================================
# WAF Fingerprints
# ==========================================================

WAF_FINGERPRINTS = {

    "Cloudflare": {

        "headers": {
            "cf-ray",
            "cf-cache-status",
            "cf-request-id",
            "cf-worker",
            "cf-mitigated",
        },

        "cookies": {
            "__cf_bm",
            "__cflb",
            "cf_clearance",
        },

        "server": {
            "cloudflare",
        },

        "body": {
            "attention required",
            "checking your browser",
            "please enable cookies",
            "cloudflare",
        },

        "status": {
            403,
            429,
            503,
        },

    },

    "Akamai": {

        "headers": {
            "akamai-grn",
            "akamai-origin-hop",
            "x-akamai",
            "x-akamai-request-id",
        },

        "cookies": {
            "ak_bmsc",
            "bm_sv",
        },

        "server": {
            "akamaighost",
        },

        "body": {
            "akamai",
        },

        "status": {
            403,
        },

    },

    "Imperva": {

        "headers": {
            "x-iinfo",
        },

        "cookies": {
            "incap_ses",
            "visid_incap",
        },

        "server": {
            "imperva",
        },

        "body": {
            "imperva",
            "incapsula",
        },

        "status": {
            403,
        },

    },

    "AWS WAF": {

        "headers": {
            "x-amzn-requestid",
            "x-amzn-trace-id",
        },

        "cookies": set(),

        "server": set(),

        "body": {
            "aws waf",
            "generated by aws waf",
        },

        "status": {
            403,
        },

    },

    "Azure Front Door": {

        "headers": {
            "x-azure-ref",
            "x-fd-healthprobe",
        },

        "cookies": {
            "arraffinity",
        },

        "server": set(),

        "body": {
            "azure front door",
        },

        "status": {
            403,
        },

    },

    "Fastly": {

        "headers": {
            "x-served-by",
            "fastly-debug-digest",
        },

        "cookies": set(),

        "server": {
            "fastly",
        },

        "body": {
            "fastly",
        },

        "status": {
            503,
        },

    },

    "Sucuri": {

        "headers": {
            "x-sucuri-id",
            "x-sucuri-cache",
        },

        "cookies": {
            "sucuri_cloudproxy_uuid",
        },

        "server": {
            "sucuri",
        },

        "body": {
            "sucuri website firewall",
        },

        "status": {
            403,
        },

    },

    "F5 BIG-IP": {

        "headers": {
            "x-waf-event-info",
            "x-wa-info",
        },

        "cookies": {
            "bigipserver",
        },

        "server": {
            "big-ip",
            "f5",
        },

        "body": {
            "big-ip",
            "f5 networks",
        },

        "status": {
            403,
        },

    },

    "Barracuda": {

        "headers": {
            "x-barracuda",
        },

        "cookies": {
            "barra_counter_session",
        },

        "server": {
            "barracuda",
        },

        "body": {
            "barracuda",
        },

        "status": {
            403,
        },

    },

    "FortiWeb": {

        "headers": {
            "x-fortiwaf",
        },

        "cookies": {
            "fortiwafsid",
        },

        "server": {
            "fortiweb",
        },

        "body": {
            "fortiweb",
        },

        "status": {
            403,
        },

    },

    "Citrix ADC": {

        "headers": {
            "x-citrix",
        },

        "cookies": {
            "ns_af",
            "nsc_",
        },

        "server": {
            "citrix",
        },

        "body": {
            "citrix adc",
        },

        "status": {
            403,
        },

    },

    "Radware AppWall": {

        "headers": {
            "x-rw",
        },

        "cookies": set(),

        "server": {
            "radware",
        },

        "body": {
            "radware",
        },

        "status": {
            403,
        },

    },

    "StackPath": {

        "headers": {
            "x-sp-edge",
        },

        "cookies": set(),

        "server": {
            "stackpath",
        },

        "body": {
            "stackpath",
        },

        "status": {
            403,
        },

    },

    "LiteSpeed": {

        "headers": {
            "x-litespeed-cache",
        },

        "cookies": set(),

        "server": {
            "litespeed",
        },

        "body": {
            "litespeed",
        },

        "status": {
            403,
        },

    },

    "ModSecurity": {

        "headers": {
            "mod_security",
            "modsecurity",
        },

        "cookies": set(),

        "server": {
            "mod_security",
            "modsecurity",
        },

        "body": {
            "modsecurity",
            "not acceptable",
        },

        "status": {
            403,
            406,
        },

    },

}

# ==========================================================
# Confidence Score
# ==========================================================

CONFIDENCE = {

    "header": 40,
    "cookie": 20,
    "server": 15,
    "body": 10,
    "status": 5,

}

# ==========================================================
# Confidence Levels
# ==========================================================

CONFIDENCE_LEVELS = (

    (80, "High"),
    (60, "Medium"),
    (40, "Low"),
    (0, "Unknown"),

)